name: Build

on: [ push, workflow_dispatch ]

permissions: read-all

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        tf-version: [ 1.1.9, 1.2.9, 1.3.2 ]
    steps:
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@a9b3e54ee0052a2f40a4eb4ca8b39dfd3bc2bc65 #v0.2.3
        with:
          image-tag: 'latest'

      - name: Install terraform v${{ matrix.tf-version }}
        run: |
          curl -LO https://releases.hashicorp.com/terraform/${{ matrix.tf-version }}/terraform_${{ matrix.tf-version }}_linux_amd64.zip
          unzip terraform_${{ matrix.tf-version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          rm *
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate examples terraform v${{ matrix.tf-version }}
        run: make examples
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
